apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-catalog-deployment
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-catalog
  template:
    metadata:
      labels:
        app: mysql-catalog
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.27
        ports:
        - containerPort: 3306
        volumeMounts:
          - name: mysql-initdb
            mountPath: /docker-entrypoint-initdb.d
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: password
          - name: MYSQL_DATABASE
            value: catalog-library
      volumes:
        - name: mysql-initdb
          configMap:
            name: mysql-catalog-initdb-config

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-catalog-service
spec:
  type: ClusterIP
  selector:
    app: mysql-catalog
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
